# Numpy Array creation and perform operation on it.

In [1]:
import numpy as np

In [2]:
myarray=np.array([[1,2,3]],np.int32)

In [3]:
myarray[0,1]

np.int32(2)

In [4]:
myarray.shape

(1, 3)

In [5]:
myarray.dtype

dtype('int32')

In [6]:
myarray

array([[1, 2, 3]], dtype=int32)

In [7]:
myarray[0,2]

np.int32(3)

In [8]:
print(myarray[0,2])

3


In [9]:
myarray.size

3

In [10]:
zero=np.zeros((4,5))

In [11]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
lspace=np.linspace(1,5,5)

In [13]:
lspace

array([1., 2., 3., 4., 5.])

In [14]:
rage=np.arange(1,10)

In [15]:
rage

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
inden=np.identity(5)

In [17]:
inden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
emp=np.empty((3,4))

In [19]:
emp

array([[1.29955443e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.70362985e+160, 5.40126150e-062,
        1.00172815e+165],
       [5.98750539e+174, 5.94084277e-038, 6.88345845e-042,
        1.45259955e-051]])

In [20]:
newarray=np.arange(20)

In [21]:
newarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
newarray=newarray.reshape(4,5)

In [23]:
newarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
newarray=newarray.ravel()

In [25]:
newarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
newarray.shape

(20,)

# Numpy Axis

In [27]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [28]:
araay=np.array(x)

In [29]:
araay

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
araay.sum(axis=0)

array([12, 15, 18])

In [31]:
araay.sum(axis=1)

array([ 6, 15, 24])

In [32]:
araay.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
for i in araay.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [34]:
araay.ndim

2

In [35]:
araay.size

9

In [36]:
araay.nbytes

72

In [37]:
oned=np.array([1,20,3,4])

In [38]:
oned

array([ 1, 20,  3,  4])

In [39]:
oned.argmax()

np.int64(1)

In [41]:
oned.argsort()

array([0, 2, 3, 1])

In [42]:
araay

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
araay.argmin()

np.int64(0)

In [45]:
araay.argmax()

np.int64(8)

In [46]:
araay.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [47]:
araay.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [48]:
araay.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])


# Numpy metrix operations

In [49]:
new1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
new1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
new2=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [52]:
new2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [53]:
new1+new2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [54]:
new2-new1

array([[ 8,  6,  4],
       [ 2,  0, -2],
       [-4, -6, -8]])

In [55]:
new1*new2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [57]:
new1/new2

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])